### ISSUE TITLE
sg_spi LCD orientation + not responding keyboard

### ISSUE THREAD

**Issue by jon19800404** [bitbank2/sg_free#1]
Hi Larry,

I appreciate your work with this emulator, which I would like to use it in my project based on a [NanoPI Neo v1.4 with 256MB RAM](https://www.friendlyelec.com/index.php?route=product/product&product_id=132). I know it is been a while now since you created this project, but unfortunately I have 2 problems :(

I am using Armbian with Kernel 5.15.48, at the moment the latest one:

```
root@nanopineo:~/Down/sg_free# uname -a
Linux nanopineo 5.15.48-sunxi #22.05.3 SMP Wed Jun 22 07:35:10 UTC 2022 armv7l GNU/Linux
```

I am using your SPI_LCD library as well, and it compiled correctly with the **spi_lcd.c** file modifications below:
```
#define USE_GENERIC
...
#define USE_NANOPINEO
```

The sample is working correctly with my **ili9341** SPI LCD:
```
root@nanopineo:~/Down/SPI_LCD# ./lcd
Full screen updates max out at 15.02 FPS
2000 random rectangles in 2286 ms
root@nanopineo:~/Down/SPI_LCD#
```
The **sg_free/sg_spi** compiled without errors, the configuration file **smartgear.config** contains these settings:
```
#
# SmartGear configuration file
#
# verbose
# The display_type can be lcd,fb0,fb1
display_type lcd
# center image on cropped display (overscan)
display_offset_x 200
display_offset_y 200

#user options
audio off
head2head off
use_framebuffer on
stretch_hq2x on

start_dir /root/Down/sg_free/roms
# SPI channel number
lcd_channel 0
# flipped = rotated 180, another value = normal orientation
lcd_orientation normal
lcd_speed 46000000
lcd_type ili9341
# piplay setup
lcd_dc 22
lcd_rst 7
lcd_led 11

# possible player controls: keyboard, gpio, gamepad0 gamepad1
p1 keyboard
p2 gamepad1

# keyboard definitions use scancodes

# ESC
key_exit 1
# arrow keys (not keypad)
key_up 103
key_down 108
key_left 105
key_right 106
# Z key
key_start 44
# B key
key_select 48
# ENTER
key_a 28
# Q
key_b 16
# W
key_c 17
# E
key_d 18

# GPIO definitions use header pin numbers (not BCM GPIO numbers)
#gpio_up 37
#gpio_down 33
#gpio_left 32
#gpio_right 31
#gpio_a 36
#gpio_b 38
#gpio_c 29
#gpio_d 40
#gpio_start 7
#gpio_select 11
#gpio_exit 40

# Gamepad definitions for cheap copy of Buffalo USB controller
gamepad_exit 4
gamepad_start 9
gamepad_select 8
gamepad_a 1
gamepad_b 2
gamepad_c 0
gamepad_d 3
```

1. The screen orientation is in PORTRAIT as you can see in the attached picture below:
[Picture of the screen](https://drive.google.com/file/d/1v0n8ejBZTqKjkO4pzj2RK-ua7QfIZ9Yb/view?usp=sharing)

2. The connected keyboard to the NanoPI Neo is a working one, but the SmartGear is not responding for any inputs at all.

Please, could you check that if I missed something with the configurations, or any other thoughts or ideas?

Thank you very much.

Bests,
Zsolt

**Comment by bitbank2** [comment]
Portrait is the native orientation of the LCD; this is the "normal" setting in the lcd_orientation parameter. Change it to 90.
I don't know why the keyboard input isn't working, but you'll need to debug that part.
