### ISSUE TITLE
Building with errors

### ISSUE THREAD

**Issue by ilyamordasov** [bitbank2/sg_free#2]
Hi, I'm trying to use your lib with pine64, and when I try to make it with GTK I get the next errors
```
/usr/bin/ld: nes.o: (.bss+0x290): multiple definition of `pBitmap`; sg_main.o:(.bss+0x180): first defined here

/usr/bin/ld: z80.o:(.bss+0×30): multiple definition of `Z8OOLDP`
gg.o: (.bss+0x10d8): first defined here

/usr/bin/ld: z80.o:(.bss+0×38): multiple definition of `Z8OOLDPC`
gg.o: (.bss+0x10d4): first defined here


collect2: error: ld returned 1 exit status
make: *** [Makefile:28: sg] Error 1
```

And if I try to make it with your spi_lcd library, I get errors with undeclared constant: `LCD_ORIENTATION_PORTRAIT` and `LCD_ORIENTATION_LANDSCAPE`

**Comment by bitbank2** [comment]
I don't want to keep you hanging, but I'm sorry that this project is very old and I've made breaking changes to dependencies like the spi_lcd library. Work through it if you can and open a PR if you have a fix.
